[package]
name = "r-debugger"
version = "0.1.0"
authors = ["takayuki tanaka <takayuki.1981.0317@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "0.23"
libc = "0.2"
symbolic-demangle = "*"
