name: r-debugger-ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install clippy
      run: rustup component add clippy
    - name: Build
      run: cargo build --verbose
    - name: clippy
      run: cargo clippy --verbose
    - name: Run tests
      run: cargo test --verbose

